### ISSUE TITLE
Distinguish between direct and transitive bogus ProjectReference

### ISSUE THREAD

**Issue by stan-sz** [dfederm/ReferenceTrimmer#48] opened 2023-02-13 07:32 UTC
Currently RT issues the same warning for a bogus `ProjectReference` regardless if its origin is in the same project file or was indirectly coming from a dependent project.

**Comment by dfederm** [comment] 2023-02-15 04:20
Can you elaborate on the bug? I may be misunderstanding as I couldn't repro with this branch: https://github.com/dfederm/ReferenceTrimmer/tree/unused-transitive-dep

**Comment by stan-sz** [comment] 2023-02-24 08:07
RT should issue different warning for `ProjectReference` in the current project file vs transitively inherited from dependencies.

**Comment by dfederm** [comment] 2023-02-24 15:11
It doesn't emit warnings for transitive dependencies at all. That's a good thing too since that's not possible to control.

**Comment by dfederm** [comment] 2023-04-05 04:44
Closing as the issue is unclear

**Comment by dfederm** [comment] 2023-09-08 23:56
Reopening with slightly different interpretation.

If A -> B -> C, and C is an unused dependency of B, then A should not *also* see the warning since it has no direct control over its transitive refs. Today both projects get the warning.

**Closed** 2023-09-09 01:00 UTC
