### ISSUE TITLE
It's breaking incremental build

### ISSUE THREAD

**Issue by seanyao1** [dfederm/ReferenceTrimmer#54] opened 2023-02-25 02:48 UTC
The build always doing this, even when there's no change on code. 
Build started...
1>------ Build started: Project: Billing.Attribution.Domain, Configuration: Debug Any CPU ------
1>Build started 2/24/2023 6:46:51 PM.
1>Target DeleteReferenceTrimmerGetUsedAssemblyReferencesFile:
1>  Deleting file "C:\Repos\vienna\src\azureml-api\src\Billing\Attribution\Domain\obj\Debug\net6.0\_ReferenceTrimmer_GetUsedAssemblyReferences.txt".
1>Target GenerateTargetFrameworkMonikerAttribute:
1>  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>Target CoreGenerateAssemblyInfo:
1>  Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
1>Target CoreCompile:
1>  CompilerServer: server - server processed compilation - 874ddd03-750d-4f8e-844c-c02120af0cb9
1>Target GenerateBuildDependencyFile:
1>  Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.

**Comment by dfederm** [comment] 2023-02-25 03:28
Dupe of #36. Fixed by #52.

**Comment by dfederm** [comment] 2023-04-05 04:43
Haven't head back, but I'm assuming this is resolved by the new version.

**Closed by dfederm** 2023-04-05 04:43 UTC
